name: Markdown linter runner

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"

jobs:
  lint:
    name: mdl runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Run Markdownlint
        run: npm run md:lint
